### ISSUE TITLE
App shows up as damaged on macOS

### ISSUE THREAD

**Issue by BogdanTheGeek** [deanthecoder/ZXSpeculator#32]
I've tried both x86 and arm64 versions and both cannot be opened on an M1 mac. Checked the permissions, tried running the binary directly, it's just not a valid executable.

**Comment by deanthecoder** [comment]
Thanks for the heads-up. Weird - It always used to work, but I downloaded 1.4 again and can see the problem too. Perhaps due to an OS X update?
Anyway, I've rebuilt the app and it now works (for me at least!)
v1.5: https://github.com/deanthecoder/ZXSpeculator/releases/tag/Release_1_5

**Comment by BogdanTheGeek** [comment]
`“ZX Speculator.app” is damaged and can’t be opened. You should eject the disk image.`
Still having the same issue (it also still shows up as V1.4 not V1.5 in the dmg title.

**Comment by BogdanTheGeek** [comment]
just as a question, why are windows files bundled with the macos app? The Contents/MacOS folder is full of *.dll and 3rdparty has an exe.

**Comment by deanthecoder** [comment]
Well this is silly.  The .dmg files work fine here, but if I upload them to github and download them again they shrink in size and become 'corrupt'!  I'll keep digging.
As to the other question - That's just how .Net works across platforms.  The Mac .Net runtime loads the 'dlls' and knows what to do with them.  They keep their .exe and .dll file extensions just to keep Windows happy, I believe.

**Comment by BogdanTheGeek** [comment]
Well, it has both .dll and .dylib
```
file Avalonia.DesignerSupport.dll
Avalonia.DesignerSupport.dll: PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows

file libAvaloniaNative.dylib
libAvaloniaNative.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
libAvaloniaNative.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libAvaloniaNative.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```
I'm not familiar at all with C# or .NET, but maybe there is an option to not include the files not needed for that platform.

**Comment by BogdanTheGeek** [comment]
ok, I managed to build it from source, easier than expected.

**Comment by deanthecoder** [comment]
Ah - It's OS X's 'quarantine' feature.
This should make the installed file work:
xattr -d com.apple.quarantine /Applications/ZX\ Speculator.app

**Comment by BogdanTheGeek** [comment]
Yep, that worked! Thanks.
